In [1]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\13616\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\13616\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\13616\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\13616\anaconda3\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [8]:
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [7]:
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print (engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [16]:
def q(sql, **params):
    with engine1.connect () as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [17]:
q("show tables")

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10         piitstdata
11           students
12          students2
13              team1

In [20]:
def q(sql, **params):
    with engine1.connect () as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [21]:
q("show tables")

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10         piitstdata
11           students
12          students2
13              team1

In [28]:
file_path = ("C:/analytics/data/piitstdata.csv")
print (file_path)

C:/analytics/data/piitstdata.csv

In [31]:
file_path=("C:/analytics/data/obisdata.csv")
print(file_path)

C:/analytics/data/obisdata.csv

In [30]:
df = pd.read_csv(file_path)
df.head(10)

  rollno  english  maths  python
0   P100       79     75      66
1   P101       71     56      91
2   P102       62     69      78
3   P103       63     57      70
4   P104       81     52      98
5   P105       85     70      94
6   P106       94     60      85
7   P107       93     84      67
8   P108       59     81      61
9   P109       70     97      86

In [32]:
file_path=("C:/analytics/data/obisdata.csv")
print(file_path)

C:/analytics/data/obisdata.csv

In [34]:
df1=pd.read_csv(file_path)
df1.head(10)

   OBJECTID        NAME  Obesity   Shape__Area  Shape__Length
0         1       Texas     32.4  7.672329e+12   1.540832e+07
1         2  California     24.2  5.327809e+12   1.451870e+07
2         3    Kentucky     34.6  1.128830e+12   6.346699e+06
3         4     Georgia     30.7  1.652980e+12   5.795596e+06
4         5   Wisconsin     30.7  1.567816e+12   6.806782e+06
5         6      Oregon     30.1  3.178446e+12   7.976011e+06
6         7    Virginia     29.2  1.158804e+12   7.710804e+06
7         8   Tennessee     33.8  1.177054e+12   6.350377e+06
8         9   Louisiana     36.2  1.355094e+12   7.383857e+06
9        10    New York     25.0  1.411441e+12   7.981383e+06

In [35]:
q('select * from mtcars limit 10')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,make_year,brand_name
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,None,None
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,None,None
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,None,None
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,None,None
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,None,None
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,None,None
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,None,None
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,None,None
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,None,None
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,None,None

In [36]:
df2 = pd.read_sql("SELECT * FROM exceldatafile1;", engine1)
df2.head()

,StudentID,FirstName,LastName,Gender,Class,AdmissionDate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,S001,Aarav,Sharma,M,12A,2024-04-15,None,ASSIGN 1,None,None,None,None,Concatinate
1,S002,Vivaan,Verma,F,12A,2024-04-21,None,StudentID,FirstName,LastName,None,None,Aarav Sharma
2,S003,Aditya,Gupta,M,12A,2024-05-19,None,S001,Aarav,Sharma,None,None,Vivaan Verma
3,S004,Vihaan,Mehta,M,12C,2024-06-11,None,S002,Vivaan,Verma,None,None,Aditya Gupta
4,S005,Arjun,Singh,M,12C,2022-06-22,None,S0007,NOTFOUND,NOTFOUND,IFERROR,None,Vihaan Mehta

#more prsctice

In [54]:
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@local host:3306/piit")
print (engine1)

Engine(mysql+pymysql://piuser:***@local host:3306/piit)

In [55]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [56]:
def q(sql,**params):
    with engine1.connect () as conn:
        return pd.read_sql(text(sql), conn, params=parms)

In [57]:
def q(sql, **params):
    with engine1.connect () as conn:
        return pd.read_sql(text(sql), conn, params=params)

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'local host' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)