In [1]:
from sqlalchemy import create_engine, text
import pandas as pd 
import os

In [7]:
engine1 = create_engine ("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [9]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [10]:
engine1= create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [11]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [12]:
engine1= create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [13]:
def q(sql,**params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [15]:
q('select * from employees')

   employee_id     name  department_id
0            1    Alice            1.0
1            2      Bob            2.0
2            3  Charlie            1.0
3            4    David            3.0
4            5      Eve            NaN

In [20]:
def q(sql,**params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [21]:
q('select * from employees')

   employee_id     name  department_id
0            1    Alice            1.0
1            2      Bob            2.0
2            3  Charlie            1.0
3            4    David            3.0
4            5      Eve            NaN

In [25]:
def q(sql,**params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [29]:
q("select * from team1")

   ser_id first_name last_name  age  Salary
0    1001    Akhansh    Mandal   26  150000
1    1002    Muhammd    Kabeer   41  150000
2    1003     Suroor     Ahmed   25  120000
3    1004   Jugartha  Halchemy   28  100000
4    1005    Nayeema    Zannat   25  100000
5    1006   Amandeep      Kaur   25  100000
6    1007    Sultana   Parveen   25  100000
7    1008     Sharan     Shaha   23  100000
8    1009     Delwar   Hossain   28  110000

##practice from the begaining ,how to fetch data from SQL to PYTHON (jupyter)

In [30]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [31]:
engine1=create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")

In [32]:
print (engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [36]:
def q(sql,**params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [37]:
q('select * from employees')

   employee_id     name  department_id
0            1    Alice            1.0
1            2      Bob            2.0
2            3  Charlie            1.0
3            4    David            3.0
4            5      Eve            NaN

In [38]:
q('show tables')

   Tables_in_piit
0         authors
1           books
2     departments
3       employees
4  exceldatafile1
5          mtcars
6        students
7       students2
8           team1

#again

In [40]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [41]:
engine1= create_engine("mysql+pymysql://piuser:Pass%40123@localhost/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost/piit)

In [49]:
def q(sql,**params):
      with engine1.connect() as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [47]:
def q(sql,**params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [48]:
q('show tables')

   Tables_in_piit
0         authors
1           books
2     departments
3       employees
4  exceldatafile1
5          mtcars
6        students
7       students2
8           team1

#final revision

In [50]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [51]:
engine1= create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")

In [52]:
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [53]:
def q(sql,**params):
    with engine1.connect () as conn:
        return pd.read_sql(text(sql),conn,params=params)

In [55]:
q('select * from students')

   student_id First_name Last_name         Major   Year_Lavel  GPA
0         101   Muhammad    Kabeer       Finance  Second Year  4.0
1         102    Akhansh    Mandal  Data Science  Second Year  4.0
2         103     Suroor     Ahmed            IT  Second Year  4.0

In [56]:
q('select first_name from students where student_id = 101,102')

ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',102' at line 1")
[SQL: select first_name from students where student_id = 101,102]
(Background on this error at: https://sqlalche.me/e/20/f405)