In [1]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine
import os

In [2]:
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
engine1

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [3]:
pd.read_sql('SHOW DATABASES;', engine1)

             Database
0  information_schema
1  performance_schema
2                piit

In [4]:
pd.read_sql('SHOW TABLES;', engine1)

   Tables_in_piit
0     departments
1       employees
2  exceldatafile1
3        students
4       students2

In [6]:
df = pd.read_sql("SELECT * FROM employees", engine1)

In [7]:
df

   employee_id     name  department_id
0            1    Alice            1.0
1            2      Bob            2.0
2            3  Charlie            1.0
3            4    David            3.0
4            5      Eve            NaN

###HOW TO WRITE TO MYSQL

In [8]:
from pydataset import data
mtcars = data('mtcars')

In [9]:
mtcars.to_sql (name='mtcars', con=engine1, if_exists='append', index=False )

32

In [10]:
pd.read_sql('SHOW TABLES;', engine1)

   Tables_in_piit
0     departments
1       employees
2  exceldatafile1
3          mtcars
4        students
5       students2

Method 2 - Python pandas-sql Method

In [16]:
pysqldf = lambda q: sqldf(q, globals())

In [18]:
import pandas as pd
from pandassql to 
import os
from pydataset import data

In [20]:
mtcars2 = data('mtcars')

In [21]:
pysqldf("SELECT * FROM mtcars2 where mpg >25;")

NameError: name 'sqldf' is not defined

In [25]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2