In [1]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [3]:
engine1=create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [4]:
def q(sql,**params):
    with engine1.connect () as conn:
        return pd.read_sql (text(sql),conn,params=params)

In [5]:
q('show tables')

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6      exceldatafile1
7              mtcars
8            obisdata
9            students
10          students2
11              team1

In [6]:
q('select * from crimedata limit 10')

Empty DataFrame
Columns: [DR_NO, Date Rptd, DATE OCC, TIME OCC, AREA, AREA NAME, Rpt Dist No, Part 1-2, Crm Cd, Crm Cd Desc, Mocodes, Vict Age, Vict Sex, Vict Descent, Premis Cd, Premis Desc, Weapon Used Cd, Weapon Desc, Status, Status Desc, Crm Cd 1, Crm Cd 2, Crm Cd 3, Crm Cd 4, LOCATION, Cross Street, LAT, LON]
Index: []

[0 rows x 28 columns]

In [7]:
q('describe crimedata')

             Field    Type Null Key Default Extra
0            DR_NO  bigint  YES        None
1        Date Rptd    text  YES        None
2         DATE OCC    text  YES        None
3         TIME OCC  bigint  YES        None
4             AREA  bigint  YES        None
5        AREA NAME    text  YES        None
6      Rpt Dist No  bigint  YES        None
7         Part 1-2  bigint  YES        None
8           Crm Cd  bigint  YES        None
9      Crm Cd Desc    text  YES        None
10         Mocodes    text  YES        None
11        Vict Age  bigint  YES        None
12        Vict Sex    text  YES        None
13    Vict Descent    text  YES        None
14       Premis Cd  double  YES        None
15     Premis Desc    text  YES        None
16  Weapon Used Cd  double  YES        None
17     Weapon Desc    text  YES        None
18          Status    text  YES        None
19     Status Desc    text  YES        None
20        Crm Cd 1  double  YES        None
21        Crm Cd 2  double  YES        None
22        Crm Cd 3  double  YES        None
23        Crm Cd 4  double  YES        None
24        LOCATION    text  YES        None
25    Cross Street    text  YES        None
26             LAT  double  YES        None
27             LON  double  YES        None

In [9]:
file_path=("c:/analytics/data/Evdata.csv")
print (file_path)

c:/analytics/data/Evdata.csv

In [10]:
df=pd.read_csv(file_path)

In [11]:
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,WA1E2AFY8R,Thurston,Olympia,WA,98512.0,2024,AUDI,Q5 E,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,23.0,0.0,22.0,263239938,POINT (-122.90787 46.9461),PUGET SOUND ENERGY INC,5.306701e+10
1,WAUUPBFF4J,Yakima,Wapato,WA,98951.0,2018,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16.0,0.0,15.0,318160860,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
2,1N4AZ0CP0F,King,Seattle,WA,98125.0,2015,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,46.0,184963586,POINT (-122.30253 47.72656),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,WA1VAAGE5K,King,Kent,WA,98031.0,2019,AUDI,E-TRON,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,204.0,0.0,11.0,259426821,POINT (-122.17743 47.41185),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,7SAXCAE57N,Snohomish,Bothell,WA,98021.0,2022,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,1.0,208182236,POINT (-122.18384 47.8031),PUGET SOUND ENERGY INC,5.306105e+10

In [13]:
df.to_sql('Evdata', engine1, if_exists='append', index=False, chunksize=1000, method='multi')

C:\Users\13616\AppData\Local\Temp\ipykernel_24284\3193548808.py:1: UserWarning: The provided table name 'Evdata' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql('Evdata', engine1, if_exists='append', index=False, chunksize=1000, method='multi')

264628

In [15]:
q('show tables')

       Tables_in_piit
0             authors
1               books
2           crimedata
3         departments
4   employee_earnings
5           employees
6              evdata
7      exceldatafile1
8              mtcars
9            obisdata
10           students
11          students2
12              team1

In [ ]:
engine1=create_engine("mysql+pymysql://piuser:Pass%40123")

In [18]:
df.to_excel('C:/analytics/data/Evdata1.csv')

ValueError: No engine for filetype: 'csv'