In [23]:
from sqlalchemy import create_engine
import pandas as pd
import os
import pymysql

In [25]:
file_path=("C:/analytics/data/obisdata.csv")
print(file_path)

C:/analytics/data/obisdata.csv

In [26]:
df=pd.read_csv(file_path)

In [27]:
df.head()

   OBJECTID        NAME  Obesity   Shape__Area  Shape__Length
0         1       Texas     32.4  7.672329e+12   1.540832e+07
1         2  California     24.2  5.327809e+12   1.451870e+07
2         3    Kentucky     34.6  1.128830e+12   6.346699e+06
3         4     Georgia     30.7  1.652980e+12   5.795596e+06
4         5   Wisconsin     30.7  1.567816e+12   6.806782e+06

In [44]:
file_path=("C:/analytics/data/employees.csv")
print(file_path)

C:/analytics/data/employees.csv

In [46]:
df = pd.read_csv(file_path)
df.head()

  employee_id;"first_name";"last_name";"department";"salary"
0                        1;"John";"Doe";"HR";55000.0
1                      2;"Jane";"Smith";"IT";60000.0
2              3;"Alice";"Johnson";"Finance";55000.0
3                    4;"Bob";"Williams";"IT";62000.0
4                     5;"Emily";"Brown";"HR";48000.0

In [47]:
file_path=("C:/analytics/data/students3.csv")
print(file_path)

C:/analytics/data/students3.csv

In [48]:
df=pd.read_csv(file_path)
df.head()

   Unnamed: 0  rollno      name  gender         dob  height program
0           0       1  Jugurtha    Male  2000-08-16     156     BCA
1           1       2  Amandeep  Female  2000-02-21     170     BBA
2           2       3    Barkat  Female  2001-07-17     158     BCA
3           3       4    Suroor  Female  2001-11-16     188     BBA
4           4       5   Sultana    Male  2001-04-02     167     BCA

In [49]:
file_path=("C:/analytics/data/CUSTOMERAGE.xlsx")
print(file_path)

C:/analytics/data/CUSTOMERAGE.xlsx

In [51]:
df=pd.read_xlsx(file_path)
df.head()

AttributeError: module 'pandas' has no attribute 'read_xlsx'

In [52]:
file_path=("C:/analytics/data/Evdata.csv")
print(file_path)

C:/analytics/data/Evdata.csv

In [53]:
df=pd.read_csv(file_path)
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,WA1E2AFY8R,Thurston,Olympia,WA,98512.0,2024,AUDI,Q5 E,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,23.0,0.0,22.0,263239938,POINT (-122.90787 46.9461),PUGET SOUND ENERGY INC,5.306701e+10
1,WAUUPBFF4J,Yakima,Wapato,WA,98951.0,2018,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16.0,0.0,15.0,318160860,POINT (-120.42083 46.44779),PACIFICORP,5.307794e+10
2,1N4AZ0CP0F,King,Seattle,WA,98125.0,2015,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,46.0,184963586,POINT (-122.30253 47.72656),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,WA1VAAGE5K,King,Kent,WA,98031.0,2019,AUDI,E-TRON,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,204.0,0.0,11.0,259426821,POINT (-122.17743 47.41185),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,7SAXCAE57N,Snohomish,Bothell,WA,98021.0,2022,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,1.0,208182236,POINT (-122.18384 47.8031),PUGET SOUND ENERGY INC,5.306105e+10