In [25]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine,text
import pymysql
import os

In [26]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\13616\anaconda3\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

In [27]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [28]:
engine1 = create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [31]:
def q(sql,** params):
    with engine1.connect() as conn:
      return pd.read_sql(text(),conn,params=params)

In [33]:
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [34]:
q('show tables')

       Tables_in_piit
0        \flight data
1        \flight_data
2             authors
3               books
4              class1
5              class2
6           crimedata
7         departments
8   employee_earnings
9           employees
10     exceldatafile1
11         flightdata
12             mtcars
13           obisdata
14            patient
15         piitstdata
16             record
17             sales1
18             sales2
19           students
20          students2
21              team1

In [36]:
q('select * from flightdata limit 5')

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [47]:
q('select Airline from flightdata where Destination ="Kolkata"')

       Airline
0    Air India
1      Vistara
2      Vistara
3    Air India
4      Vistara
..         ...
376     IndiGo
377   SpiceJet
378     IndiGo
379     IndiGo
380     IndiGo

[381 rows x 1 columns]

In [51]:
q('select Airline,Source from flightdata where Price>6000')

                Airline    Source
0             Air India   Kolkata
1           Jet Airways     Delhi
2                IndiGo   Kolkata
3                IndiGo  Banglore
4           Jet Airways  Banglore
...                 ...       ...
7511        Jet Airways  Banglore
7512  Multiple carriers     Delhi
7513        Jet Airways  Banglore
7514            Vistara  Banglore
7515          Air India     Delhi

[7516 rows x 2 columns]