In [3]:
pip install pydataset

Requirement already satisfied: pydataset in c:\users\13616\anaconda3\lib\site-packages (0.2.0)
Requirement already satisfied: pandas in c:\users\13616\anaconda3\lib\site-packages (from pydataset) (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\13616\anaconda3\lib\site-packages (from pandas->pydataset) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\13616\anaconda3\lib\site-packages (from pandas->pydataset) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\13616\anaconda3\lib\site-packages (from pandas->pydataset) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\13616\anaconda3\lib\site-packages (from pandas->pydataset) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\13616\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->pydataset) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from pydataset import data

In [5]:
print (data())

        dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

In [6]:
cake = data('cake')
cake.head()

   replicate recipe  temperature  angle  temp
1          1      A          175     42   175
2          1      A          185     46   185
3          1      A          195     47   195
4          1      A          205     39   205
5          1      A          215     53   215

In [7]:
cake.tail()

     replicate recipe  temperature  angle  temp
266         15      C          185     28   185
267         15      C          195     25   195
268         15      C          205     25   205
269         15      C          215     31   215
270         15      C          225     25   225

In [8]:
type(cake)

pandas.core.frame.DataFrame

mtcars = data('mtcars')

mtcars.head()

In [9]:
cbpp = data ('cbpp')

In [10]:
cbpp.head()

   herd  incidence  size  period
1     1          2    14       1
2     1          3    12       2
3     1          4     9       3
4     1          0     5       4
5     2          3    22       1

In [11]:
mtcars = data ('mtcars')

In [12]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [13]:
type(cbpp)

pandas.core.frame.DataFrame

In [14]:
type(mtcars)

pandas.core.frame.DataFrame

In [15]:
mtcars.notnull().sum(axis=0)

mpg     32
cyl     32
disp    32
hp      32
drat    32
wt      32
qsec    32
vs      32
am      32
gear    32
carb    32
dtype: int64

In [16]:
mtcars.notnull().sum(axis=1)

Mazda RX4              11
Mazda RX4 Wag          11
Datsun 710             11
Hornet 4 Drive         11
Hornet Sportabout      11
Valiant                11
Duster 360             11
Merc 240D              11
Merc 230               11
Merc 280               11
Merc 280C              11
Merc 450SE             11
Merc 450SL             11
Merc 450SLC            11
Cadillac Fleetwood     11
Lincoln Continental    11
Chrysler Imperial      11
Fiat 128               11
Honda Civic            11
Toyota Corolla         11
Toyota Corona          11
Dodge Challenger       11
AMC Javelin            11
Camaro Z28             11
Pontiac Firebird       11
Fiat X1-9              11
Porsche 914-2          11
Lotus Europa           11
Ford Pantera L         11
Ferrari Dino           11
Maserati Bora          11
Volvo 142E             11
dtype: int64

In [17]:
mtcars.duplicated()

Mazda RX4              False
Mazda RX4 Wag          False
Datsun 710             False
Hornet 4 Drive         False
Hornet Sportabout      False
Valiant                False
Duster 360             False
Merc 240D              False
Merc 230               False
Merc 280               False
Merc 280C              False
Merc 450SE             False
Merc 450SL             False
Merc 450SLC            False
Cadillac Fleetwood     False
Lincoln Continental    False
Chrysler Imperial      False
Fiat 128               False
Honda Civic            False
Toyota Corolla         False
Toyota Corona          False
Dodge Challenger       False
AMC Javelin            False
Camaro Z28             False
Pontiac Firebird       False
Fiat X1-9              False
Porsche 914-2          False
Lotus Europa           False
Ford Pantera L         False
Ferrari Dino           False
Maserati Bora          False
Volvo 142E             False
dtype: bool

In [18]:
mtcars.duplicated().sum()

np.int64(0)

In [19]:
mtcars.notnull().sum().sum()

np.int64(352)

In [20]:
mtcars.duplicated(subset=['gear','carb','am','cyl']).sum()

np.int64(18)

In [21]:
mtcars.notnull().sum().sum()

np.int64(352)

In [22]:
mtcars.max(axis=0)

mpg      33.900
cyl       8.000
disp    472.000
hp      335.000
drat      4.930
wt        5.424
qsec     22.900
vs        1.000
am        1.000
gear      5.000
carb      8.000
dtype: float64

In [23]:
mtcars.mean(axis=1)

Mazda RX4              29.907273
Mazda RX4 Wag          29.981364
Datsun 710             23.598182
Hornet 4 Drive         38.739545
Hornet Sportabout      53.664545
Valiant                35.049091
Duster 360             59.720000
Merc 240D              24.634545
Merc 230               27.233636
Merc 280               31.860000
Merc 280C              31.787273
Merc 450SE             46.430909
Merc 450SL             46.500000
Merc 450SLC            46.350000
Cadillac Fleetwood     66.232727
Lincoln Continental    66.058545
Chrysler Imperial      65.972273
Fiat 128               19.440909
Honda Civic            17.742273
Toyota Corolla         18.814091
Toyota Corona          24.888636
Dodge Challenger       47.240909
AMC Javelin            46.007727
Camaro Z28             58.752727
Pontiac Firebird       57.379545
Fiat X1-9              18.928636
Porsche 914-2          24.779091
Lotus Europa           24.880273
Ford Pantera L         60.971818
Ferrari Dino           34.508182
Maserati Bora          63.155455
Volvo 142E             26.262727
dtype: float64