In [20]:
from pydataset import data
import pandas as pd
from sqlalchemy import create_engine,text
import os

In [21]:
df=pd.read_csv("C:/analytics/data/students2.csv")

In [22]:
print(df)

    rollno        name  gender         dob  height program
0        1    Jugurtha    Male  2000-08-16     156     BCA
1        2    Amandeep  Female  2000-02-21     170     BBA
2        3      Barkat  Female  2001-07-17     158     BCA
3        4      Suroor  Female  2001-11-16     188     BBA
4        5     Sultana    Male  2001-04-02     167     BCA
5        6      Sajjad    Male  2000-10-12     153     BCA
6        7      Sharan    Male  2000-07-28     174     BBA
7        8    Djedjiga  Female  2000-06-27     163     BCA
8        9      Bijata  Female  2002-05-14     158     BBA
9       10      Mahadi  Female  2000-03-06     175     BCA
10      11      Sundas    Male  2000-03-02     151     BCA
11      12      Mandal    Male  2000-07-10     169     BBA
12      13      Najmul  Female  2001-03-23     177     BCA
13      14       Deniz    Male  2001-04-21     156     BBA
14      15     Sharmin    Male  2002-10-31     157     BCA
15      16       Emran    Male  2000-02-24     184     BBA
16      17      Sundas    Male  2001-02-11     163     BBA
17      18     Tanzeel  Female  2002-05-09     166     BCA
18      19  Student_19    Male  2001-03-27     185     BCA
19      20  Student_20    Male  2002-07-08     189     BBA
20      21  Student_21  Female  2001-07-23     153     BCA
21      22  Student_22    Male  2000-01-14     151     BCA
22      23  Student_23    Male  2000-11-22     155     BCA
23      24  Student_24     NaN  2002-05-15     153     BBA
24      25  Student_25  Female  2001-11-27     178     BBA
25      26  Student_26     NaN  2001-07-23     167     BBA
26      27  Student_27    Male  2000-11-14     175     BBA
27      28  Student_28  Female  2001-03-16     183     BBA
28      29  Student_29  Female  2001-11-20     159     BBA
29      30  Student_30    Male  2000-07-28     185     BBA

In [23]:
df.to_csv('C:/analytics/data/students4.csv')

In [24]:
engine1=("mysql+pymysql:/piuser:Pass%40123@localhost:3306/piit")
print(engine1)

mysql+pymysql:/piuser:Pass%40123@localhost:3306/piit

In [36]:
def q(sql,**params):
    with engine1.connect () as conn:
        return pd.read_sql (text(sql),conn,params=params)

In [39]:
def q(sql,**params):
    with engine1.connect () as conn:
        return pd.read_sql (text(sql),conn,params=params)

In [40]:
q('show tables')

AttributeError: 'str' object has no attribute 'connect'

In [41]:
from sqlalchemy import create_engine,text
import pandas as pd
import os

In [42]:
engine1=create_engine("mysql+pymysql://piuser:Pass%40123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [43]:
def q(sql,**params):
    with engine1.connect () as conn:
        return pd.read_sql (text(sql),conn,params=params)

In [44]:
q('show tables')

       Tables_in_piit
0             authors
1               books
2              class1
3              class2
4           crimedata
5         departments
6   employee_earnings
7           employees
8      exceldatafile1
9              mtcars
10           obisdata
11            patient
12         piitstdata
13             record
14           students
15          students2
16              team1

In [45]:
q('select * from class1 limit 5')

   roll_no first_name last_name  nationality  age  gender  score
0        1   AKHANGSH    MANDAL       NEPALI   24    MALE    879
1        2     SUROOR    AHMAED     AMERICAN   25  FEMALE    857
2        3   MUHAMMAD    KABEER  BANGLADESHI   40    MALE    873
3        4    NAYEEMA    ZANNAT  BANGLADESHI   24  FEMALE    832
4        5   JUGARTHA  HALCHEMI      TURKISH   30    MALE    798